name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Actions cannot access secrets so pass them in as inputs
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: eu-north-1

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Install dependencies
        run: |
          pipenv sync --dev

      - name: Test
        env:
          BUILDING_MODE: dev
          PYTHONPATH: "src"
        run: |
          pipenv run coverage run --source=src -m pytest -q
          pipenv run coverage report -m --omit="*/tests/*"

      - name: Build
        run: python -m build
